WebApp/Models/ErrorViewModel.cs
using System;

namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApp/Models/Note.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class Note
    {
        [Key]
        public int No { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Contents { get; set; }

        [Required]
        public int UserNo { get; set; }

        [ForeignKey("UserNo")]
        public virtual User User { get; set; }
    }
}

WebApp/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class User
    {
        [Key]
        public int No { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Id { get; set; }

        [Required]
        public string Password { get; set; }

    }
}

WebApp/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApp.DataContext;
using WebApp.Models;
using WebApp.ViewModel;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WebApp.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (var db = new WebAppDbContext())
                {
                    var user = db.Users.FirstOrDefault(u => u.Id.Equals(model.Id)
                                                        && u.Password.Equals(model.Password));
                    if (user != null) // Login Success
                    {
                        //HttpContext.Session.SetInt32(key, value);
                        HttpContext.Session.SetInt32("USER_LOGIN_KEY", user.No);
                        return RedirectToAction("LoginSuccess", "Home");
                    }
                } 
                // Login Failed
                ModelState.AddModelError(string.Empty, "Incorrect ID or Password");
            }
            return View(model);
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Remove("USER_LOGIN_KEY");

            return RedirectToAction("Index", "Home");
        }


        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(User model)
        {
            if (ModelState.IsValid)
            {
                //try catch
                using (var db = new WebAppDbContext())
                {
                    db.Users.Add(model);    // update in memory
                    db.SaveChanges();       // save in sql
                }
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }
    }
}

WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            //var firstUser = new User
            //{
            //    No = 1,
            //    Name = "Inhyup"
            //};

            ////ViewBag.User = firstUser;

            //ViewData["User"] = firstUser;
            return View();
        }

        public IActionResult LoginSuccess()
        {
            return View();
        }


        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/Controllers/NoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApp.DataContext;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class NoteController : Controller
    {
        public IActionResult Index()
        {
            if (HttpContext.Session.GetInt32("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }

            using (var db = new WebAppDbContext())
            {
                var list = db.Notes.ToList();
                return View(list);
            }
        }

        public IActionResult Detail(int noteNo)
        {
            if (HttpContext.Session.GetInt32("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }
            using (var db = new WebAppDbContext())
            {
                var note = db.Notes.FirstOrDefault(n => n.No.Equals(noteNo));
                return View(note);
            }
        
        }

        public IActionResult Add()
        {
            if (HttpContext.Session.GetInt32("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }

            return View();
        }

        [HttpPost]
        public IActionResult Add(Note model)
        {
            if (HttpContext.Session.GetInt32("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }

            model.UserNo = int.Parse(HttpContext.Session.GetInt32("USER_LOGIN_KEY").ToString());

            if (ModelState.IsValid)
            {
                using (var db = new WebAppDbContext())
                {
                    db.Notes.Add(model);
                    if (db.SaveChanges() > 0)
                    {
                        return Redirect("Index");
                    }
                }
                ModelState.AddModelError(string.Empty, "Can't save your note");
            }
            return View(model);
        }

        public IActionResult Edit()
        {
            if (HttpContext.Session.GetInt32("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        public IActionResult Delete()
        {
            if (HttpContext.Session.GetInt32("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }
    }
}

WebApp/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.IO;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WebApp.Controllers
{
    public class UploadController : Controller
    {
        private readonly IHostingEnvironment _environment;

        public UploadController(IHostingEnvironment environment)
        {
            _environment = environment;
        }
        

        [HttpPost]
        [Route("api/upload")]
        public async Task<IActionResult> ImageUpload(IFormFile file)
        {
            // 파일 업로드 할 떄 필요한 것
            // 1. path
            var path = Path.Combine(_environment.WebRootPath, @"images\upload");
            // 2. name
            // 3. extension - jpg, txt 
            var fileFullName = file.FileName.Split('.');
            var fileName = $"{Guid.NewGuid()}.{fileFullName[1]}";
            using (var fileStream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
            {
                await file.CopyToAsync(fileStream);
            }
            return Ok(new { file = "/images/upload/" + fileName, success = true });

        }
    }
}

WebApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

WebApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApp/Views/Home/Index.cshtml
@*<h1>@Model.No</h1>

<h1>@Model.Name</h1>*@

@*<h2>@ViewBag.User.No</h2>
<h2>@ViewBag.User.Name</h2>*@


WebApp/Views/Home/LoginSuccess.cshtml
<h1>Login Success</h1>

WebApp/Views/Note/Add.cshtml
@model WebApp.Models.Note

<h1>Add</h1>

<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
        <form class="form-horizontal" method="post" asp-controller="Note" asp-action="Add">
            <div class="text-danger" asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label>Title</label>
                <input type="text" class="form-control" asp-for="Title" placeholder="Type Title" />
                <span class="text-danger" asp-validation-for="Title"></span>
            </div>

            <div class="form-group">
                <label>Content</label>
                <textarea class="form-control editor" rows="10" asp-for="Contents" placeholder="Type Contents"> </textarea>
                <span class="text-danger" asp-validation-for="Contents"></span>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">save</button>
                <a class="btn btn-default" asp-controller="Note" asp-action="Index">cancel</a>
            </div>
        </form>
    </div>
    <div class="col-lg-2"></div>
</div>

WebApp/Views/Note/Detail.cshtml

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Detail - @Model.Title</h3>
    </div>

</div>

<div class="row">
    <div class="col-lg-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                <label>TItle: </label>@Model.Title
            </div>
            <div class="panel-body">
                @Html.Raw(Model.Contents)
            </div>
            <div class="panel-footer text-right">
                <a class="btn btn-primary" asp-controller="Note" asp-action="Index">List</a>
            </div>
        </div>
    </div>
</div>


WebApp/Views/Note/Edit.cshtml
<h1>Edit</h1>

WebApp/Views/Note/Index.cshtml

<h1>게시판</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>No</th>
            <th>Title</th>
            <th>Writer</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var note in Model)
        {
            <tr>
                <td>@note.No</td>
                <td>
                    <a asp-controller="Note" asp-action="Detail" asp-route-noteNO="@note.No">@note.Title</a>
                </td>
                <td>@note.UserNo</td>
            </tr>
        }
    </tbody>
</table>

<a class="btn btn-warning" asp-controller="Note" asp-action="Add">Add Note</a>

WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/trumbowyg/dist/ui/trumbowyg.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Note" asp-action="Index">Note</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Context.Session.GetInt32("USER_LOGIN_KEY") == null)
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Register">Register</a></li>
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - WebApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/trumbowyg/dist/trumbowyg.min.js"></script>
        <script src="~/lib/trumbowyg/dist/plugins/upload/trumbowyg.upload.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>